name: Ping Supabase to Prevent Pausing

on:
  schedule:
    - cron: "0 9 * * *" # Runs every day at 9:00 AM UTC
  workflow_dispatch: # Allows manual triggering from GitHub UI

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: "npm"

      - name: Cache npm dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-cache-${{ runner.os }}-${{ hashFiles('package-lock.json', '.nvmrc') }}
          restore-keys: npm-cache-${{ runner.os }}-

      - name: Install dependencies
        run: npm ci

      - name: Ping Supabase Users Table
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        run: |
          node -e "
          (async () => {
            try {
              const { createClient } = require('@supabase/supabase-js');

              const supabase = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_SERVICE_ROLE_KEY, {
                auth: { persistSession: false }
              });

              const { data, error } = await supabase.from('recipes').select().limit(1);

              if (error) throw error;

              console.log('Ping successful!');
            } catch (err) {
              console.error('Error pinging Supabase:', err.message);
              process.exit(1);
            }
          })();
          "
