name: Ping Supabase to Prevent Pausing

on:
  schedule:
    - cron: "0 8 * * 1,4" # Runs at 8:00 AM UTC (12:00 AM PST, 1:00 AM PDT) on Mondays and Tuesdays
  workflow_dispatch: # Allows manual triggering from GitHub UI

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Ping Supabase Users Table
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        run: |
          node -e "
          (async () => {
            try {
              const { createClient } = require('@supabase/supabase-js');

              const supabase = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_SERVICE_ROLE_KEY, {
                auth: { persistSession: false }
              });

              const { data, error } = await supabase.from('recipes').select().limit(1);

              if (error) throw error;

              console.log('Ping successful!');
            } catch (err) {
              console.error('Error pinging Supabase:', err.message);
              process.exit(1);
            }
          })();
          "
